config/routes.rb
Bookshop::Application.routes.draw do
  root :to => 'authors#index'

  resources :authors, :books
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  dob        :date
#  image      :text
#  bio        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Author < ActiveRecord::Base
  attr_accessible :name, :dob, :image, :bio
  has_many :books
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  author_name :string(255)
#  genre       :string(255)
#  image       :text
#  author_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Book < ActiveRecord::Base
    attr_accessible :title, :author_name, :genre, :image, :author_id
    belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    author = Author.create(params[:author]) #what is happening here?
    redirect_to(author)
  end

  def edit
    @author = Author.find(params[:id])
  end

  def show
    @author = Author.find(params[:id])
  end

  def update
    author = Author.find(params[:id]) #find the author
    author.update_attributes(params[:author]) #update this author
    redirect_to(author)
  end

  def destroy
    author = Author.find(params[:id])
    author.destroy
    redirect_to(authors_path)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new # this displays the form for input new book details
    @book = Book.new
  end

  def create #after the form has been submitted. Create and write book details to db and then display list of books
    book = Book.create(params[:book])
    redirect_to(book) #where are we redirecting
  end

  def show # show a particular book details
    @book = Book.find(params[:id])
  end

  def edit #edit a specific book - display on screen and then go to update
    @book = Book.find(params[:id])
  end

  def update # this gets called after operator enters sumbit after form is filled in.
    book = Book.find(params[:id]) # find the specific book details
    book.update_attributes(params[:book]) # update the book details on database. only col's that have changed.
  end

  def destroy
    book = Book.find(params[:id]) #find the book to be deleted
    book.destroy
    redirect_to(books_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :dob %>
  <%= f.text_field :dob%>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <%= f.label :bio %>
  <%= f.text_field :bio %>
  <br>
  <%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<h1> Edit Author </h1>
<%= render :partial => 'form' %>

app/views/authors/index.html.erb
<div class = 'detail'>
  <% @authors.each do |author| %>
    <ul class='item'>
      <li><%= image_tag(author.image, :class => 'image_size') %></li>
      <li><%= link_to(author.name, author, :class => 'author' )%></li>
      <li><%= author.bio %></li>
      <li><%= author.dob.strftime('%B %d %y') %></li>
    </ul>
  <% end %>
</div>

app/views/authors/new.html.erb
<h1> Add Author </h1>
<%= render :partial => 'form' %>

app/views/authors/show.html.erb
      <li><%= @author.name %></li>
      <li><%= @author.bio %></li>
      <li><%= @author.dob.strftime('%B %d %y') %></li>

<!-- the line below gives you the list to the artist you want to delete -->
<%= link_to 'delete', @author, :method => :delete %>
<%= link_to 'edit', edit_author_path(@author) %>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :author_name %>
  <%= f.text_field :author_name%>
  <br>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <!-- this gets the author names and id's from the database. Map comes from functional programming.  f.select is the dropdown [author.name, author.id - it displays the author.name in the dropdown-->
  <%= f.label :author_id %>
  <%= f.select :author_id, Author.all.map {|author| [author.name, author.id]} %>
  <br>
  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1> Edit Book </h1>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<div class = 'detail'>
  <% @books.each do |book| %>
    <ul class = 'item'>
      <li><%= image_tag(book.image, :class => 'image_size') %></li>
      <li><%= link_to(book.title, book, :class => 'author' )%></li>
      <li><%= book.genre %></li>
      <li><%= book.author_name %></li>
    </ul>
  <% end %>
</div>

app/views/books/new.html.erb
<h1> Add book </h1>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
      <li><%= @book.title %></li>
      <li><%= image_tag(@book.image, :class => 'image_size') %></li>
      <li><%= @book.genre %></li>
      <li><%= @book.author_name %></li>
<%= link_to 'delete', @book, :method => :delete %>
<%= link_to 'edit', edit_book_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
    <ul>
      <li><%= link_to('new author', new_author_path) %></li>
      <li><%= link_to('new book', new_book_path) %></li>
    </ul>
  </nav>
<%= yield %>

</body>
</html>